name: Link to Trello

on:
  pull_request:
    types: [ "created", "edited" ]

jobs:
  trello:
    runs-on: ubuntu-latest

    steps:
      - name: Test secrets
        run: |
          test -n "{{ secrets.TRELLO_KEY }}"
          test -n "{{ secrets.TRELLO_TOKEN }}"
      - name: Attach PR to trello cards
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_EVENT"
